# Generated by Django 6.1.1 on 2026-09-12 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_link',
            field=models.URLField(default='https://github.com/placeholder/placeholder'),
            preserve_default=False,
        ),
    ]
